[Stevens]
source        = maildir://~/Mail/stevens/
outgoing      = smtp+insecure://dliu4@stevens.edu@127.0.0.1:1025
default       = INBOX
archive       = Archive
from          = Dan Liu <dliu4@stevens.edu>
copy-to       = Sent
# pgp-auto-sign = true
# pgp-attach-key = true
