[School]
source        = maildir://~/mail/
outgoing      = smtp+insecure://dliu4@stevens.edu@127.0.0.1:1025
default       = stevens/INBOX/
from          = Dan Liu <dliu4@stevens.edu>
copy-to       = Sent
# pgp-auto-sign = true
# pgp-attach-key = true


# [nad2040 Gmail]
# source        = maildir://~/mail/
# outgoing      = smtp+insecure://@127.0.0.1:1025
# default       = stevens/INBOX
# from          = Dan Liu <dliu4@stevens.edu>
# copy-to       = Sent
#
